add "Banana Cake Pop" app
electron/apps pull request #2053
Opened 2022-09-03 20:54 UTC by rstaib

## Adding a new application

### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [ ] My application is open-source and has been created for at least 20 days
- [x] My application is closed-source and here is a proof it uses Electron:

![Evidence](https://user-images.githubusercontent.com/4325318/188287266-99454342-1234-46d4-847b-af0111cb64ca.png)

### Description

**Banana Cake Pop** is a cross-platform GraphQL IDE built for developers.

You'll find more info at [bananacakepop.com](https://bananacakepop.com).

We've also a cloud version running at [eat.bananacakepop.com](https://eat.bananacakepop.com).

![Screenshot 1](https://user-images.githubusercontent.com/4325318/188287278-e40f03db-4eb6-4c52-a1fa-0b807b1da621.png)

![Screenshot 2](https://user-images.githubusercontent.com/4325318/188287168-ac7b7acf-2c27-48a8-bd9d-30168a0c8d71.png)

![Screenshot 3](https://user-images.githubusercontent.com/4325318/188287179-1d71927d-e3f9-40e0-b4e0-e972bec042c2.png)

2022-09-13 17:53 UTC, ckerr approved these changes
This looks pretty cool. Thanks for the PR!

2022-09-13 17:54 UTC, ckerr requested changes
App LGTM but there are a couple of minor changes needed to the PR to make CI happy:

```
18966 passing (2s)
  2 failing

  1) human-submitted app data
       banana-cake-pop
         banana-cake-pop.yml
           description
             should end with a period / full stop:

      AssertionError: Description should end in a period / full stop: 'Cross-platform GraphQL IDE built for developers': expected 's' to equal '.'
      + expected - actual

      -s
      +.
      
      at Context.<anonymous> (test/human-data.js:72:70)
      at processImmediate (internal/timers.js:461:21)

  2) human-submitted app data
       banana-cake-pop
         icon
           is between 256px x 256px and 1024px x 1024px:
     AssertionError: expected [12](https://github.com/electron/apps/actions/runs/2985754110/jobs/4911030158#step:5:13)8 to be within 256..1024
      at Context.<anonymous> (test/human-data.js:250:42)
      at processImmediate (internal/timers.js:461:[21](https://github.com/electron/apps/actions/runs/2985754110/jobs/4911030158#step:5:22)
```

2022-09-14 14:16 UTC, rstaib commented
> App LGTM but there are a couple of minor changes needed to the PR to make CI happy:
> 
> ```
> 18966 passing (2s)
>   2 failing
> 
>   1) human-submitted app data
>        banana-cake-pop
>          banana-cake-pop.yml
>            description
>              should end with a period / full stop:
> 
>       AssertionError: Description should end in a period / full stop: 'Cross-platform GraphQL IDE built for developers': expected 's' to equal '.'
>       + expected - actual
> 
>       -s
>       +.
>       
>       at Context.<anonymous> (test/human-data.js:72:70)
>       at processImmediate (internal/timers.js:461:21)
> 
>   2) human-submitted app data
>        banana-cake-pop
>          icon
>            is between 256px x 256px and 1024px x 1024px:
>      AssertionError: expected [12](https://github.com/electron/apps/actions/runs/2985754110/jobs/4911030158#step:5:13)8 to be within 256..1024
>       at Context.<anonymous> (test/human-data.js:250:42)
>       at processImmediate (internal/timers.js:461:[21](https://github.com/electron/apps/actions/runs/2985754110/jobs/4911030158#step:5:22)
> ```

@ckerr Could you please check again? Fixed the issues.

2022-09-14 18:26 UTC, ckerr approved these changes

2022-09-14 18:26 UTC, merged